name: 'Checkout'
description: 'Checkout a Git repository.'
inputs: 
  repository:
    description: 'Repository name'
  ref:
    description: 'Ref to checkout (SHA, branch, tag)'
  token:
    description: 'Access token for clone repository'
  clean:
    description: 'If true, execute `execute git clean -ffdx && git reset --hard HEAD` before fetching'
    default: true
  submodules:
    description: 'Whether to recursively clone submodules; defaults to false'
  lfs:
    description: 'Whether to download Git-LFS files; defaults to false'
  fetch-depth:
    description: 'The depth of commits to ask Git to fetch; defaults to no limit'  
  path:
    description: 'Optional path to check out source code'  
runs:
  plugin: 'checkout'
